{% set name = "types-Markdown" %}
{% set version = "3.7.0.20240822" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-Markdown-{{ version }}.tar.gz
  sha256: 183557c9f4f865bdefd8f5f96a38145c31819271cde111d35557c3bd2069e78d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/markdown-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for Markdown
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
