{% set version = "3.8.0.20250809" %}
{% set python_min = python_min | default("3.9") %}

package:
  name: types-markdown
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/types-markdown/types_markdown-{{ version }}.tar.gz
  sha256: fa619e735878a244332a4bbe16bcfc44e49ff6264c2696056278f0642cdfa223

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
    - test -f $SP_DIR/markdown-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for Markdown
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
