{% set name = "types-Markdown" %}
{% set version = "3.7.0.20241204" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_').lower() }}-{{ version }}.tar.gz
  sha256: ecca2b25cd23163fd28ed5ba34d183d731da03e8a5ed3a20b60daded304c5410

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/markdown-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for Markdown
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
