schema_version: 1

context:
  version: 3.10.2.20260211

package:
  name: types-markdown
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/types-markdown/types_markdown-${{ version }}.tar.gz
  sha256: 66164310f88c11a58c6c706094c6f8c537c418e3525d33b76276a5fbd66b01ce

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - setuptools
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}

tests:
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - pip check

  - package_contents:
      site_packages:
        - markdown-stubs/__init__.pyi

about:
  summary: Typing stubs for Markdown
  license: Apache-2.0 AND MIT
  license_file: LICENSE
  homepage: https://github.com/python/typeshed

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
